package com.ollama.ollama.ai.service;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpMethod;
import org.springframework.http.ResponseEntity;

@Service
public class AIService {

    private final ObjectMapper objectMapper = new ObjectMapper();

    @Value("${spring.ai.ollama.base-url}")
    private String baseUrl;

    @Value("${spring.ai.ollama.chat.options.model}")
    private String model;

    private final RestTemplate restTemplate = new RestTemplate();

    // Method to generate a summary using the Ollama model
    public String generateSummary(String meetingText) {
        String url = baseUrl + "/api/chat"; // Define the endpoint for Ollama chat model
        HttpHeaders headers = new HttpHeaders();
        headers.set("Content-Type", "application/json");

        // Create the request body
        String requestBody = "{\"input\": \"" + meetingText + "\", \"model\": \"" + model + "\"}";

        // Create an HttpEntity with the body and headers
        HttpEntity<String> entity = new HttpEntity<>(requestBody, headers);

        // Send the POST request to Ollama API (local setup)
        ResponseEntity<String> response = restTemplate.exchange(url, HttpMethod.POST, entity, String.class);

        // Return the summary
        return response.getBody();  // Assuming the body is the summary generated by the model
    }

    // Method to extract action items from the summary
    public String extractActionItems(String summary) {
        // Here you could extract action items from the summary and return them as a JSON string
        String actionItemsJson = "[\"Action Item 1: Follow up on project deadlines.\", \"Action Item 2: Schedule a team meeting.\"]";
        return actionItemsJson; // Return the string directly
    }

    // Method to extract risks from the summary
    public String extractRisks(String summary) {
        // Here you could extract risks from the summary and return them as a JSON string
        String risksJson = "[\"Risk 1: Potential delays due to lack of resources.\", \"Risk 2: Miscommunication among team members.\"]";
        return risksJson; // Return the string directly
    }
}
